In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv('E:/Works/10. Mental Health Disorder/Dataset/Dataset 1/Suicide_Detection.csv')
df1.head()

   Unnamed: 0                                               text        class
0           2  Ex Wife Threatening SuicideRecently I left my ...      suicide
1           3  Am I weird I don't get affected by compliments...  non-suicide
2           4  Finally 2020 is almost over... So I can never ...  non-suicide
3           8          i need helpjust help me im crying so hard      suicide
4           9  I’m so lostHello, my name is Adam (16) and I’v...      suicide

In [4]:
df2 = pd.read_csv('E:/Works/10. Mental Health Disorder/Dataset/Dataset 2/Depression_Suicide.csv')
df2.head()

,content,datetime,label
0,misstoriblack cool i have no tweet applic for...,2009-04-06 23:11:14,neutral
1,tiannachao i know just famili drama it lamehey...,2009-06-23 13:40:11,neutral
2,school email wont open and i have geographi st...,2009-06-01 10:26:07,neutral
3,piginthepok oh whi are you feel like that,2009-06-19 16:11:29,neutral
4,gahh noopeyton need to livethi is horribl,2009-05-11 22:01:32,neutral

In [5]:
# Drop the first column
df1 = df1.drop(df1.columns[0], axis=1)
df1.head()

                                                text        class
0  Ex Wife Threatening SuicideRecently I left my ...      suicide
1  Am I weird I don't get affected by compliments...  non-suicide
2  Finally 2020 is almost over... So I can never ...  non-suicide
3          i need helpjust help me im crying so hard      suicide
4  I’m so lostHello, my name is Adam (16) and I’v...      suicide

In [6]:
# Drop the first column
df2 = df2.drop(df2.columns[1], axis=1)
df2.head()

                                             content    label
0  misstoriblack cool  i have no tweet applic for...  neutral
1  tiannachao i know just famili drama it lamehey...  neutral
2  school email wont open and i have geographi st...  neutral
3          piginthepok oh whi are you feel like that  neutral
4          gahh noopeyton need to livethi is horribl  neutral

In [7]:
df1.isnull().sum()

text     0
class    0
dtype: int64

In [8]:
df2.isnull().sum()

content    0
label      0
dtype: int64

In [9]:
# Manually encode the labels
label_mapping = {'non-suicide': 0, 'suicide': 2}
df1['class'] = df1['class'].map(label_mapping)
df1.head()

                                                text  class
0  Ex Wife Threatening SuicideRecently I left my ...      2
1  Am I weird I don't get affected by compliments...      0
2  Finally 2020 is almost over... So I can never ...      0
3          i need helpjust help me im crying so hard      2
4  I’m so lostHello, my name is Adam (16) and I’v...      2

In [10]:
# Count occurrences of each label
df1['class'].value_counts()

class
2    116037
0    116037
Name: count, dtype: int64

In [11]:
# Manually encode the labels
label_mapping = {'neutral': 0, 'depression': 1, 'suicide': 2}
df2['Label'] = df2['label'].map(label_mapping)
df2.head()

                                             content    label  Label
0  misstoriblack cool  i have no tweet applic for...  neutral      0
1  tiannachao i know just famili drama it lamehey...  neutral      0
2  school email wont open and i have geographi st...  neutral      0
3          piginthepok oh whi are you feel like that  neutral      0
4          gahh noopeyton need to livethi is horribl  neutral      0

In [12]:
# Count occurrences of each label
df2['Label'].value_counts()

Label
1    391043
2    386934
0    290422
Name: count, dtype: int64

In [13]:
# Filter out rows where 'class' is 0 or 2
df2 = df2[~df2['Label'].isin([0, 2])]
df2.head()

                                                  content       label  Label
290422  most day i wonder whi do i do the thing i do w...  depression      1
290423  im so far gone iv been depress for about 6 yea...  depression      1
290424  sorri for the super long post but i need to ve...  depression      1
290425  today i am go to think differently not forever...  depression      1
290426  im in depression again this is the worst feel ...  depression      1

In [14]:
# Count occurrences of each label
df2['Label'].value_counts()

Label
1    391043
Name: count, dtype: int64

In [15]:
# Drop the first column
df2 = df2.drop(df2.columns[1], axis=1)
df2.head()

                                                  content  Label
290422  most day i wonder whi do i do the thing i do w...      1
290423  im so far gone iv been depress for about 6 yea...      1
290424  sorri for the super long post but i need to ve...      1
290425  today i am go to think differently not forever...      1
290426  im in depression again this is the worst feel ...      1

In [16]:
# Rename 'class' column to 'labels' in df1
df1 = df1.rename(columns={'class': 'Label'})
df2 = df2.rename(columns={'content': 'text'})

In [17]:
# Concatenate df1 and df2
merged_df = pd.concat([df1, df2], ignore_index=True)

# Shuffle the dataset
df = merged_df.sample(frac=1).reset_index(drop=True)
df.head()

                                                text  Label
0  i am tire of go through the same thing everyda...      1
1  i still rememb the moment well it was a wet co...      1
2  Help me please I am in the bra section of a st...      0
3  i am complet miserable my wife is absolut beau...      1
4  Self destructionIs it just me or am I losing m...      2

In [18]:
# Count occurrences of each label
df['Label'].value_counts()

Label
1    391043
0    116037
2    116037
Name: count, dtype: int64

In [20]:
df.to_csv('E:/Works/10. Mental Health Disorder/Dataset/2_types_raw_data.csv', index=False)

In [21]:
# Filter the dataset to get 1,00,000 samples for each label
label_0 = df[df['Label'] == 0].sample(n=100000, random_state=1)
label_1 = df[df['Label'] == 1].sample(n=100000, random_state=1)
label_2 = df[df['Label'] == 2].sample(n=100000, random_state=1)

# Concatenate these samples into a single dataframe
df_balanced = pd.concat([label_0, label_1, label_2])

# Shuffle the concatenated dataframe
df = df_balanced.sample(frac=1, random_state=1).reset_index(drop=True)
df.head(10)

                                                text  Label
0  Not sure I want to carry on.Just got out of a ...      2
1  im onli 22f so i havent had a ton of jobs but ...      1
2  Even Google knows Tiktok is a spyware http://i...      0
3  iv been want to move to anoth countri and get ...      1
4  Does October of 2002 borns have a bigger age g...      0
5  background on me im 19 and of asian descent so...      1
6                   why im leavinghealth problems.        2
7   my only requirements https://imgur.com/a/pMEBmGC      0
8  Couple yearsI’ll give it a few years and reass...      2
9  Omg my dad's new car is so fucking satisfying ...      0

In [22]:
# Count occurrences of each label
df['Label'].value_counts()

Label
2    100000
1    100000
0    100000
Name: count, dtype: int64

In [23]:
df.to_csv('E:/Works/10. Mental Health Disorder/Dataset/2_types_3lakh.csv', index=False)

In [25]:
import pandas as pd
import nltk
from nltk.corpus import words
from nltk.tokenize import word_tokenize
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer, WordNetLemmatizer

In [35]:
# Download necessary NLTK data
nltk.download('words')
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('stopwords', quiet=True)
nltk.download('omw-1.4')  # Optional for WordNet Lemmatizer

[nltk_data] Downloading package words to
[nltk_data]     C:\Users\joypa\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\joypa\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\joypa\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\joypa\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [27]:
# Initialize objects for stemming and lemmatization
stemmer = SnowballStemmer(language='english')
lemmatizer = WordNetLemmatizer()

In [28]:
# Load English words set
english_words = set(words.words())

In [29]:
# Function to filter non-English words for Labels 0 and 2
def filter_non_english_basic(text):
    return ' '.join([word for word in text.split() if word.lower() in english_words])

In [30]:
# Extend the list with common stemmed and lemmatized forms
extended_english_words = set()

for word in english_words:
    # Add the original word
    extended_english_words.add(word)
    # Add the stemmed version of the word
    extended_english_words.add(stemmer.stem(word))
    # Add the lemmatized version of the word
    extended_english_words.add(lemmatizer.lemmatize(word))

# Function to filter non-English words for Label 1
def filter_non_english_extended(text):
    return ' '.join([word for word in text.split() if word.lower() in extended_english_words])

In [31]:
# Function to apply the correct filter based on label
def conditional_filter(text, label):
    if label == 1:
        return filter_non_english_extended(text)
    else:
        return filter_non_english_basic(text)

In [32]:
# Apply the filter conditionally
df['filtered_text_eng'] = df.apply(lambda row: conditional_filter(row['text'], row['Label']), axis=1)

In [33]:
# Function for text preprocessing
def preprocess_text(text):

    # Remove URL
    text = re.sub(r'((www\.[^\s]+)|(https?://[^\s]+))', '', text)
    text = re.sub(r'#([^\s]+)', '', text)

    # Remove all the special characters
    text = re.sub(r'\W', ' ', text)

    # Remove all single characters
    text = re.sub(r'\s+[a-zA-Z]\s+', ' ', text)

    # Remove single characters from the start
    text = re.sub(r'\^[a-zA-Z]\s+', ' ', text)

    # Remove numeric
    text = re.sub(r'\d+', '', text)

    # Substituting multiple spaces with single space
    text = re.sub(r'\s+', ' ', text, flags=re.I)

    # Convert to Lowercase
    text = text.lower()

    # Remove whitespace at begin and end string
    text = text.strip()

    # Tokenize the text
    words = word_tokenize(text)

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]

    # Stemming
    words = [stemmer.stem(word) for word in words]

    # Lemmatization
    words = [lemmatizer.lemmatize(word) for word in words]

    # Join the words back into a string
    processed_text = ' '.join(words)

    return words, processed_text

In [36]:
# Apply preprocessing to the 'Text' column
df['tokenized_text'], df['Preprocessed_Text'] = zip(*df['filtered_text_eng'].apply(preprocess_text))
df.head(20)

,text,Label,filtered_text_eng,tokenized_text,Preprocessed_Text
0,Not sure I want to carry on.Just got out of a ...,2,Not sure I want to carry got out of a long las...,"[sure, want, carri, got, long, last, long, dis...",sure want carri got long last long distanc rel...
1,im onli 22f so i havent had a ton of jobs but ...,1,onli so i havent had a ton of but most of them...,"[on, havent, ton, feel, like, perform, signif,...",on havent ton feel like perform signif wor fir...
2,Even Google knows Tiktok is a spyware http://i...,0,Even is a Filler filler filler filler filler f...,"[even, filler, filler, filler, filler, filler,...",even filler filler filler filler filler filler...
3,iv been want to move to anoth countri and get ...,1,been want to move to anoth countri and get a b...,"[want, move, anoth, countri, get, better, pay,...",want move anoth countri get better pay job got...
4,Does October of 2002 borns have a bigger age g...,0,Does of have a bigger age gap with March of Is...,"[bigger, age, gap, march, big, age, abl, relat]",bigger age gap march big age abl relat
5,background on me im 19 and of asian descent so...,1,background on me and of asian descent so my pa...,"[background, asian, descent, parent, realli, c...",background asian descent parent realli care lo...
6,why im leavinghealth problems.,2,why,[],
7,my only requirements https://imgur.com/a/pMEBmGC,0,my only,[],
8,Couple yearsI’ll give it a few years and reass...,2,Couple give it a few and At that point if I ke...,"[coupl, give, point, keep, go, downward, traje...",coupl give point keep go downward trajectori h...
9,Omg my dad's new car is so fucking satisfying ...,0,my new car is so satisfying a brand new and he...,"[new, car, satisfi, brand, new, let, drive, pa...",new car satisfi brand new let drive park lot d...
10,ill never get better i dont think i ever will ...,1,ill never get better i dont think i ever will ...,"[ill, never, get, better, dont, think, ever, k...",ill never get better dont think ever kill on o...
11,Third day of expressing my emotions to strange...,0,Third day of my to through poetry I blissful d...,"[third, day, poetri, bliss, decept, silenc, vi...",third day poetri bliss decept silenc violenc p...
12,i dont have anywher to vent so i guess my best...,1,i dont have anywher to vent so i guess my best...,"[dont, anywh, vent, guess, best, bet, regard, ...",dont anywh vent guess best bet regard previous...
13,i work in healthcare today i was ask to look a...,1,i work in today i was ask to look after a pati...,"[work, today, ask, look, patient, harass, last...",work today ask look patient harass last day sa...
14,Trouble at home So at home my mum and dad stil...,0,Trouble at home So at home my mum and dad stil...,"[troubl, home, home, mum, dad, still, live, to...",troubl home home mum dad still live togeth lik...
15,my parent think im lazi and tired they dont un...,1,my parent think lazi and tired they dont under...,"[parent, think, lazi, tire, dont, understand, ...",parent think lazi tire dont understand like mo...
16,add my snap jove.luna im really bored and i ha...,0,add my snap really and i have nothing better t...,"[add, snap, realli, noth, better, plea, dri]",add snap realli noth better plea dri
17,hi friends anyon here have ani problem with sl...,1,hi anyon here have ani problem with sleep too ...,"[hi, anyon, ani, problem, sleep, much, past, t...",hi anyon ani problem sleep much past three day...
18,I don't even know where to start...I just feel...,2,I even know where to just feel like falling I ...,"[even, know, feel, like, fall, use, hold, onto...",even know feel like fall use hold onto like wa...
19,I dont even have the strength to lie and prete...,2,I dont even have the strength to lie and prete...,"[dont, even, strength, lie, pretend, smile, sa...",dont even strength lie pretend smile say every...

In [37]:
df.isnull().sum()

text                 0
Label                0
filtered_text_eng    0
tokenized_text       0
Preprocessed_Text    0
dtype: int64

In [38]:
df.shape

(300000, 5)

In [39]:
df.to_csv('E:/Works/10. Mental Health Disorder/Dataset/2_types_preprocessed_3lakh.csv', index=False, encoding='utf-8')

In [40]:
df.head(20)

,text,Label,filtered_text_eng,tokenized_text,Preprocessed_Text
0,Not sure I want to carry on.Just got out of a ...,2,Not sure I want to carry got out of a long las...,"[sure, want, carri, got, long, last, long, dis...",sure want carri got long last long distanc rel...
1,im onli 22f so i havent had a ton of jobs but ...,1,onli so i havent had a ton of but most of them...,"[on, havent, ton, feel, like, perform, signif,...",on havent ton feel like perform signif wor fir...
2,Even Google knows Tiktok is a spyware http://i...,0,Even is a Filler filler filler filler filler f...,"[even, filler, filler, filler, filler, filler,...",even filler filler filler filler filler filler...
3,iv been want to move to anoth countri and get ...,1,been want to move to anoth countri and get a b...,"[want, move, anoth, countri, get, better, pay,...",want move anoth countri get better pay job got...
4,Does October of 2002 borns have a bigger age g...,0,Does of have a bigger age gap with March of Is...,"[bigger, age, gap, march, big, age, abl, relat]",bigger age gap march big age abl relat
5,background on me im 19 and of asian descent so...,1,background on me and of asian descent so my pa...,"[background, asian, descent, parent, realli, c...",background asian descent parent realli care lo...
6,why im leavinghealth problems.,2,why,[],
7,my only requirements https://imgur.com/a/pMEBmGC,0,my only,[],
8,Couple yearsI’ll give it a few years and reass...,2,Couple give it a few and At that point if I ke...,"[coupl, give, point, keep, go, downward, traje...",coupl give point keep go downward trajectori h...
9,Omg my dad's new car is so fucking satisfying ...,0,my new car is so satisfying a brand new and he...,"[new, car, satisfi, brand, new, let, drive, pa...",new car satisfi brand new let drive park lot d...
10,ill never get better i dont think i ever will ...,1,ill never get better i dont think i ever will ...,"[ill, never, get, better, dont, think, ever, k...",ill never get better dont think ever kill on o...
11,Third day of expressing my emotions to strange...,0,Third day of my to through poetry I blissful d...,"[third, day, poetri, bliss, decept, silenc, vi...",third day poetri bliss decept silenc violenc p...
12,i dont have anywher to vent so i guess my best...,1,i dont have anywher to vent so i guess my best...,"[dont, anywh, vent, guess, best, bet, regard, ...",dont anywh vent guess best bet regard previous...
13,i work in healthcare today i was ask to look a...,1,i work in today i was ask to look after a pati...,"[work, today, ask, look, patient, harass, last...",work today ask look patient harass last day sa...
14,Trouble at home So at home my mum and dad stil...,0,Trouble at home So at home my mum and dad stil...,"[troubl, home, home, mum, dad, still, live, to...",troubl home home mum dad still live togeth lik...
15,my parent think im lazi and tired they dont un...,1,my parent think lazi and tired they dont under...,"[parent, think, lazi, tire, dont, understand, ...",parent think lazi tire dont understand like mo...
16,add my snap jove.luna im really bored and i ha...,0,add my snap really and i have nothing better t...,"[add, snap, realli, noth, better, plea, dri]",add snap realli noth better plea dri
17,hi friends anyon here have ani problem with sl...,1,hi anyon here have ani problem with sleep too ...,"[hi, anyon, ani, problem, sleep, much, past, t...",hi anyon ani problem sleep much past three day...
18,I don't even know where to start...I just feel...,2,I even know where to just feel like falling I ...,"[even, know, feel, like, fall, use, hold, onto...",even know feel like fall use hold onto like wa...
19,I dont even have the strength to lie and prete...,2,I dont even have the strength to lie and prete...,"[dont, even, strength, lie, pretend, smile, sa...",dont even strength lie pretend smile say every...